version: '3'
services:
  app:
    container_name: data-storage-service
    build:
        context: ./DataStorageService
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - spring-cloud-network

  postgres:
    container_name: postgres
    image: "postgres:14"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reto
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
          driver: bridge
